# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Martin Schröder <info@swedishembedded.com>

manifest:
  self:
    path: control

  remotes:
    - name: swedishembedded
      url-base: https://github.com/swedishembedded
  projects:
    - name: sdk
      remote: swedishembedded
      revision: main
