#!/bin/bash

mkdir build
cd build
cmake \
	-D"CMAKE_CXX_FLAGS=-g -O2 -w -fprofile-arcs -ftest-coverage" \
	-D"CMAKE_C_FLAGS=-g -O2 -w -fprofile-arcs -ftest-coverage" ..
make
make test
ctest -T Coverage
../scripts/coverage
cpack
cd ..
