#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Martin Schröder <info@swedishembedded.com>
# Consulting: https://swedishembedded.com/go
# Training: https://swedishembedded.com/tag/training

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"

LC_ALL=C sort -u -o \
	${ROOT}/CODEOWNERS \
	${ROOT}/CODEOWNERS
