#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Martin Schröder <info@swedishembedded.com>
# Consulting: https://swedishembedded.com/go
# Training: https://swedishembedded.com/tag/training

[[ -d build ]] && rm -rf build

mkdir -p build
cd build
cmake \
	-D"CMAKE_CXX_FLAGS=-g -O2 -w -fprofile-arcs -ftest-coverage" \
	-D"CMAKE_C_FLAGS=-g -O2 -w -fprofile-arcs -ftest-coverage" ..
make -j4
make test
ctest -T Coverage
../scripts/coverage
cd ..
